### ISSUE TITLE
Add Energy Calibration Functions

### ISSUE THREAD

**Issue by slwatkins** [ucbpylegroup/RQpy#1]
Energy calibration function should be added to `rqpy/core` under a new file, perhaps called `calibration.py`.

Note: any helper functions should have an underscore prepended to their names, since they aren't functions that a user will use on its own. For example, the `norm` function used with `find_peak` should likely be renamed to `_norm`.

**Comment by slwatkins** [comment]
@cwfink Is these anything else that needs to be done with regards to this issue? Seems like we've got everything.

**Comment by cwfink** [comment]
We might have everything. I'm going through a calibration now and see what else might be helpful to add. So lets keep this open for now

**Comment by slwatkins** [comment]
With PR #43 merged, we can now mark this as closed.
