### ISSUE TITLE
NameError in fit_saturation

### ISSUE THREAD

**Issue by slwatkins** [ucbpylegroup/RQpy#12]
When I submitted PR #10, I forgot to update one of the function calls at [Line 209](https://github.com/ucbpylegroup/RQpy/blob/master/rqpy/core/_fitting.py#L209) in the `fit_saturation` function. 

```
popt, pcov = curve_fit(_saturation_func, x, y, sigma=yerr, p0=guess, absolute_sigma=True, maxfev=10000)
```
Should be:
```
popt, pcov = curve_fit(utils.saturation_func, x, y, sigma=yerr, p0=guess, absolute_sigma=True, maxfev=10000)
```

I figure that it is best to do this and issue #11 at the same time.

**Comment by cwfink** [comment]
This was fixed with issue https://github.com/ucbpylegroup/RQpy/issues/11 

9e274f894ba22174a028011b8c55131b5f94b97e
