### ISSUE TITLE
non-int input into logspace

### ISSUE THREAD

**Issue by nick-mast** [ucbpylegroup/RQpy#168]
https://github.com/ucbpylegroup/RQpy/blob/684277f45291fdcd9c8dd63d77d677b783ab4337/rqpy/limit/_limit.py#L399

Just tried out sensitivity_estimate_demo for the first time and got an error here. Looks like 1e5 just needs to be cast as an int.

**Comment by slwatkins** [comment]
Nice catch, I'll make the fix now.

FYI, the reason this wasn't caught until now was because this was deprecated in a recent NumPy release, so old versions actually supported calling it in this way (though with a deprecation warning).

**Comment by slwatkins** [comment]
Committed to master, 65f1372aa71d63d0b620b9bac75a21b4217617ba
