### ISSUE TITLE
Best place to put tools for IV analysis

### ISSUE THREAD

**Issue by cwfink** [ucbpylegroup/RQpy#21]
I'm putting together a template notebook for doing IV/dIdV sweep analyses. I need to put some helper functions somewhere in RQpy, but I don't feel like they will be used for anything put making very specific plots. 

@slwatkins, do you think it would be better to create a folder under rqpy/ called iv_analysis_tools (or something similar) and place all related helper function there? that way they will all be more or less hidden from the main usage of rqpy.

Or should I just make them hidden functions somewhere else?

I sort of prefer making the iv_analysis_tools folder.

**Comment by cwfink** [comment]
So I decided to instead make all the IV sweep analysis related functions contained within a single class. 

I'm not sure if this class should live at the same level as processing, plotting, etc, or if it should live under core

**Comment by cwfink** [comment]
I ended up placing the ```IVanalysis``` class under rqpy/core/ in the file ```_iv_didv_tools.py```, see PR https://github.com/ucbpylegroup/RQpy/pull/28

Will close this issue once the PR is approved by @slwatkins

**Comment by slwatkins** [comment]
I've approved @cwfink's PR #28, so I'm closing this issue.
