### ISSUE TITLE
Change default legend location for rqpy.scatter?

### ISSUE THREAD

**Issue by slwatkins** [ucbpylegroup/RQpy#45]
I was reading through the `ax.legend` docstring, and I noticed this comment:

> The 'best' option can be quite slow for plots with large amounts of data. Your plotting speed may benefit from providing a specific location.

Maybe this is why some of our scatter plots take so long to make.. I've done some preliminary tests, and it does seem faster to plot with specifying the location.

https://matplotlib.org/api/_as_gen/matplotlib.pyplot.legend.html

**Comment by cwfink** [comment]
done with commit https://github.com/ucbpylegroup/RQpy/commit/93f68e37209d657b72456e324d3b812392904128
