### ISSUE TITLE
Create demos for the most useful functions

### ISSUE THREAD

**Issue by slwatkins** [ucbpylegroup/RQpy#48]
We should write some demo notebooks for the most useful functionality in this package, e.g.:

- Processing
- Binned cut function
- IO functions
- Plotting functions

**Comment by cwfink** [comment]
We should probably make a documentation page for `RQpy` as well.

**Comment by cwfink** [comment]
Reopening because we should still add a few more demos:
* IV/dIdV analysis
* Energy Calibration
* OI code (?)

**Comment by slwatkins** [comment]
Closing as RQpy is being archived and this is no longer relevant.
