### ISSUE TITLE
pulse sim improvements

### ISSUE THREAD

**Issue by william-page** [ucbpylegroup/RQpy#53]
Basic improvements that should be added to the bare bones functionality in #52:

- interpolate the template for time delays that are not bin integers

- add functionality for inputting a second fake pulse

- indicate in the saved pulse file that the data is fake, perhaps by adding a 4th entry into to the trigtypes ndarray

- allow MIDAS file writing

**Comment by william-page** [comment]
The first two items above (time shift interpolation and the option to add a second pulse) are now part of the pulse sim.

After some further thinking and discussion, there are two other improvements that should be added:

- some way to save the truth information (e.g. time delays, amplitudes) of the fake pulse. these saved values ideally would be in the same files as the fake pulses themselves, so that the two are never separated

- a way to input an arbitrary number of pulses to produce complex pulse shapes. for the time being this is low priority

**Comment by slwatkins** [comment]
I've added MIDAS file writing. However, the MIDAS file writing functions in scdmsPyTools are out of date and will cause segmentation faults. I think that once that is figured out, we can probably merge to master, if we are happy with saving the truth information to various parts of the file that are not being used. We can open another issue for that if not perhaps?

I've also refactored the code a little bit and removed camelCase in favor of lowercase, as is Python convention!

**Comment by slwatkins** [comment]
MIDAS file writing seems to work now with the proper version of scdmsPyTools. I've created a pull request, #60.

**Comment by slwatkins** [comment]
The pulse simulation has been merged in PR #60. I'll close this issue, but we may want to re-open (or make a different issue) if we want to work on the other improvements discussed.

**Comment by slwatkins** [comment]
Re-opening to say that I've added the arbitrary number of templates changes on the `improvement/pulsesim` branch.

Not sure how we should save the truth information in this case... Any ideas?

**Comment by slwatkins** [comment]
I think this should be good to go with PR #63 merged. There is an open question for truth information for MIDAS files when we have multiple pulse templates, but that isn't high priority now.
