### ISSUE TITLE
add convtoamps arg to acquire_pulses, acquire_randoms

### ISSUE THREAD

**Issue by william-page** [ucbpylegroup/RQpy#65]
are the acquire_pulses and acquire_randoms functions, which call loadstanfordfile, able to apply a scaling factor to the acquired traces other than the default 1/1024? From a quick look it seems that the default 1/1024 scaling cannot be overridden when calling these functions.

reference links:
loadstanfordfile: https://github.com/ucbpylegroup/RQpy/blob/master/rqpy/io/_load.py#L518
acquire_randoms: https://github.com/ucbpylegroup/RQpy/blob/master/rqpy/process/_trigger.py#L475

**Comment by slwatkins** [comment]
At the time, I believe Francisco and I had figured out the conversion from the units of the MATLAB DAQ to Amps, so I just threw the 1/1024 scaling in there and figured it would not be changing. Should be a quick fix!

Just curious, what is the correct conversion to Amps now?

**Comment by slwatkins** [comment]
Added in PR #91.
