### ISSUE TITLE
Optimum R0 is passed to _plot_energy_res_vs_bias in Ohms, but should be mOhms

### ISSUE THREAD

**Issue by slwatkins** [ucbpylegroup/RQpy#77]
In the `rqpy.plotting._plot_energy_res_vs_bias` function, the parameter `optimum_r0` is expected to be in units of mOhms, but the `rqpy.IVanalysis.find_optimum_bias` method passes it in units of Ohms, which causes the plot to not show the the point where the optimum resistance is.

Also, note that the label for this point says optimum QET bias, but the x-axis is resistance. There is a QET bias x-axis, but I'm not sure that the axis is scaling correctly, since the relationship between R_0 and QET bias is nonlinear.

https://github.com/ucbpylegroup/RQpy/blob/07dc71c7d7833a56e5ff48859fd2e4a99814883f/rqpy/core/_iv_didv_tools.py#L922-L928

https://github.com/ucbpylegroup/RQpy/blob/07dc71c7d7833a56e5ff48859fd2e4a99814883f/rqpy/plotting/_plotting.py#L991

**Comment by cwfink** [comment]
Yeah, this function needs a little work. I was on the fence about whether or not it was a useful feature, and never really finished it. I’ll re work it a bit, and also get rid of the interpolation, because it doesn’t always seem to work.

**Comment by slwatkins** [comment]
Fixed in #81.
